// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DB struct {
	Hosts                []*Record `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	BlockName            []string  `protobuf:"bytes,2,rep,name=block_name,json=blockName,proto3" json:"block_name,omitempty"`
	BlockIp              []string  `protobuf:"bytes,3,rep,name=block_ip,json=blockIp,proto3" json:"block_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DB) Reset()         { *m = DB{} }
func (m *DB) String() string { return proto.CompactTextString(m) }
func (*DB) ProtoMessage()    {}
func (*DB) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_8206c1eadac2b734, []int{0}
}
func (m *DB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DB.Unmarshal(m, b)
}
func (m *DB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DB.Marshal(b, m, deterministic)
}
func (dst *DB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DB.Merge(dst, src)
}
func (m *DB) XXX_Size() int {
	return xxx_messageInfo_DB.Size(m)
}
func (m *DB) XXX_DiscardUnknown() {
	xxx_messageInfo_DB.DiscardUnknown(m)
}

var xxx_messageInfo_DB proto.InternalMessageInfo

func (m *DB) GetHosts() []*Record {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *DB) GetBlockName() []string {
	if m != nil {
		return m.BlockName
	}
	return nil
}

func (m *DB) GetBlockIp() []string {
	if m != nil {
		return m.BlockIp
	}
	return nil
}

type Record struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_db_8206c1eadac2b734, []int{1}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *Record) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*DB)(nil), "main.DB")
	proto.RegisterType((*Record)(nil), "main.Record")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_db_8206c1eadac2b734) }

var fileDescriptor_db_8206c1eadac2b734 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x4a, 0xe2, 0x62, 0x72, 0x71,
	0x12, 0x52, 0xe2, 0x62, 0xcd, 0xc8, 0x2f, 0x2e, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36,
	0xe2, 0xd1, 0x03, 0xc9, 0xe9, 0x05, 0xa5, 0x26, 0xe7, 0x17, 0xa5, 0x04, 0x41, 0xa4, 0x84, 0x64,
	0xb9, 0xb8, 0x92, 0x72, 0xf2, 0x93, 0xb3, 0xe3, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x98,
	0x35, 0x38, 0x83, 0x38, 0xc1, 0x22, 0x7e, 0x89, 0xb9, 0xa9, 0x42, 0x92, 0x5c, 0x1c, 0x10, 0xe9,
	0xcc, 0x02, 0x09, 0x66, 0xb0, 0x24, 0x3b, 0x98, 0xef, 0x59, 0xa0, 0x64, 0xc6, 0xc5, 0x06, 0x31,
	0x4a, 0x48, 0x82, 0x8b, 0xbd, 0x20, 0xb1, 0xa4, 0x24, 0xb5, 0x28, 0x4f, 0x82, 0x51, 0x81, 0x11,
	0xa4, 0x06, 0xca, 0x15, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x02, 0x0b, 0x83,
	0xd9, 0x49, 0x6c, 0x60, 0x87, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x18, 0x6e, 0x18,
	0xb4, 0x00, 0x00, 0x00,
}
